package sfdc.service.sfdc_service_demo.connection;

public enum SFTP_STATUS {
    CONNECT, DISCONNECT, LIBRARY_ERROR, AUTHENTICATION_ERROR, UNKNOWN_HOST, CONNECTION_REFUSED, SFTP_ERROR, NOT_FOUND_FILE, ONLY_IMAGE, IOE, NOT_ALLOW_FILE_TYPE, NOT_VALID_PATH
}
